# Generated by Django 5.0.4 on 2024-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('credit_hours', models.IntegerField()),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
